name: airfly
description: "轻巧优雅的多端同步工具 - 云中转剪切板与文件共享"
publish_to: 'none'

version: 2.3.0+5

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: 12.2.0
  forui: 0.25.0
  liquid_glass_widgets: ^1.3.0
  open_filex: 4.7.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  web_socket_channel: ^3.0.3
  uuid: ^4.5.1
  path: ^1.9.1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true